# Generated by Django 2.0.6 on 2018-06-15 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'Suggested'), ('1', 'Revision'), ('2', 'Rewriting'), ('3', 'Refused'), ('4', 'Accepted')], max_length=1)),
                ('rec_total', models.SmallIntegerField()),
                ('rec_completed', models.SmallIntegerField()),
                ('deleted', models.BooleanField()),
                ('text', models.CharField(max_length=80000)),
                ('keywords', models.CharField(max_length=300)),
                ('paper_type', models.CharField(max_length=100)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_author', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_publilsher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_publish', 'Can supervise revision process'), ('can_manage', 'Can change state of process for given article')),
            },
        ),
        migrations.CreateModel(
            name='Qlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paper.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Recension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80000)),
                ('qlog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paper.Qlog')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.CharField(max_length=6000)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='recension',
            field=models.ManyToManyField(to='paper.Recension'),
        ),
        migrations.AddField(
            model_name='paper',
            name='reviewer',
            field=models.ManyToManyField(related_name='paper_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
