# Generated by Django 2.0.6 on 2018-06-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recension',
            name='qlog',
        ),
        migrations.DeleteModel(
            name='Qlog',
        ),
    ]
